--- 
name: rhodes-system-api-samples
bbver: 4.2
sdk: /Users/lars/Dev/code/rhomobile/rhodes
applog: rholog.txt
version: 1.0.6
vendor: rhomobile
 
iphone: 
  sdk: iphonesimulator3.0
  entitlements: ""
  codesignidentity: ""
  configuration: Debug

android:
  mapping: yes

