--- 
name: rhodes-system-api-samples
capabilities: 
- gps
- pim
- camera
- vibrate
- phone
bbver: 4.6.1
android: 
  capabilities: 
  - network_state
  mapping: true
sdk: /Users/brian/work/rhodes
applog: rholog.txt
version: 1.0.7
vendor: rhomobile
iphone: 
  sdk: iphonesimulator4.0
  codesignidentity: ""
  entitlements: ""
  configuration: Debug
extensions: ["rhodes_translator", "json"]