require 'fileutils'

USE_STLPORT = true


def build_extension(name, arch, src_files)
  objects = []
  mkdir_p $tempdir unless File.exists? $tempdir

  #Dir.glob("*.c").each do |f|
  src_files.each do |f|
    objname = File.join( $tempdir, File.basename( f.gsub(/\.c$/, '.o') ) )
    objects << objname

    args = []
    args << "-I."
    args << "-I#{$rootdir}/platform/android/Rhodes/jni/include"
    args << "-I#{$rootdir}/platform/shared/ruby/include"
    args << "-I#{$rootdir}/platform/shared"
    args << "-I#{$rootdir}/platform/shared/common"

    args << "-D__SGI_STL_INTERNAL_PAIR_H" if USE_STLPORT
    args << "-D__NEW__" if USE_STLPORT
    args << "-I#{$rootdir}/platform/shared/ruby/linux"
    args << "-I#{$rootdir}/platform/shared/ruby/generated"
    args << "-I#{$rootdir}/platform/shared/stlport/stlport" if USE_STLPORT

    cc_compile f, $tempdir, args or exit 1

  end

  mkdir_p $targetdir unless File.exist? $targetdir

  cc_ar File.join( $targetdir, 'lib' + name + '.a' ), Dir.glob($tempdir + "/**/*.o") or exit 1

end

namespace "build" do
  task :config do
    curdir = pwd
    $rainbowdir = curdir.gsub('/ext/rainbow/platform/android','');
    $targetdir = ENV['TARGET_TEMP_DIR']
    raise "TARGET_TEMP_DIR is not set" if $targetdir.nil?
    $tempdir = ENV['TEMP_FILES_DIR']
    raise "TEMP_FILES_DIR is not set" if $tempdir.nil?
    $rootdir = ENV['RHO_ROOT']
    raise "RHO_ROOT is not set" if $rootdir.nil?

    require File.join($rootdir, 'platform/android/build/androidcommon.rb')

    setup_ndk(ENV['ANDROID_NDK'],ENV['ANDROID_API_LEVEL'])

  end

  task :all => :config do

    src_files = []

    src_files << $rainbowdir + '/ext/rainbow/platform/android/jni/src/rainbow.cpp'
    src_files << $rainbowdir + '/ext/rainbow/shared/ruby/rainbow_wrap.c'

    # build native part
    build_extension('Rainbow', $arch, src_files)

    #build java part
    javafiles = []	
    File.open('ext_build.files', "r") do |f|
        while line = f.gets
           javafiles << line
        end
    end

    flname = $targetdir + '/ext_build.files'
    File.open(flname, "w") do |f|
        javafiles.each do |j|
            f.puts $rainbowdir + '/' + j
        end
    end

  end
end

task :default => "build:all"
