#ifdef __cplusplus
extern "C" {
#endif

// declare Ruby registration method generated by SWIG in nlist_wrap.c
extern void Init_NList(void);

// this method executed once on start of program
void Init_NList_extension(void) {
	// execute initialization of Ruby registration (generated by SWIG)
	Init_NList();

	// You can add some code to this place:


}

#ifdef __cplusplus
} //extern "C"
#endif